-- ==========================================
-- SEED EXERCISES DATA
-- ==========================================

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Barbell Bench Press', 'Chest', ARRAY['Triceps', 'Front Delts'], 'Barbell', 'Intermediate', '["Lie flat on the bench with your eyes under the bar.","Grip the bar slightly wider than shoulder-width.","Unrack the bar and lower it slowly to your mid-chest.","Press the bar back up in a slight arc to the starting position."]'::jsonb, '["Bouncing the bar off the chest","Flaring elbows at 90 degrees","Lifting glutes off the bench"]'::jsonb, '["Always use a spotter when lifting heavy weights.","Keep your wrists straight to avoid injury."]'::jsonb, '90-120 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Incline Dumbbell Press', 'Chest', ARRAY['Triceps', 'Front Delts'], 'Dumbbell', 'Intermediate', '["Set an adjustable bench to a 30-45 degree angle.","Sit back with a dumbbell in each hand resting on your thighs.","Kick the weights up to shoulder height and press them straight up.","Lower the dumbbells slowly until you feel a stretch in your chest, then press back up."]'::jsonb, '["Setting the incline too steep, targeting shoulders instead of chest","Clinking dumbbells together at the top"]'::jsonb, '["Control the descent to avoid tearing a pectoral muscle."]'::jsonb, '90-120 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Push-ups', 'Chest', ARRAY['Triceps', 'Front Delts', 'Core'], 'Bodyweight', 'Beginner', '["Start in a high plank position with hands slightly wider than shoulder-width.","Lower your body until your chest nearly touches the floor.","Keep your core engaged and back straight.","Push back up to the starting position."]'::jsonb, '["Sagging the hips","Looking straight down, dropping the neck","Flaring elbows out too wide"]'::jsonb, '["Avoid overarching the lower back to prevent lumbar pain."]'::jsonb, '60 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Pull-ups', 'Back', ARRAY['Biceps', 'Lats', 'Rear Delts'], 'Bodyweight', 'Advanced', '["Grab the pull-up bar with an overhand grip slightly wider than shoulder-width.","Hang freely with your arms fully extended.","Pull yourself up by driving your elbows down until your chin clears the bar.","Lower yourself back down with control."]'::jsonb, '["Using momentum (kipping) instead of pure strength","Not using a full range of motion"]'::jsonb, '["Warm up your shoulders properly before performing heavy pull-ups."]'::jsonb, '90-120 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Barbell Row', 'Back', ARRAY['Biceps', 'Lats', 'Lower Back'], 'Barbell', 'Intermediate', '["Stand with feet shoulder-width apart, holding a barbell with an overhand grip.","Hinge at the hips, keeping your back straight and nearly parallel to the floor.","Pull the barbell towards your lower chest/upper abdomen.","Lower the bar slowly back to the starting position."]'::jsonb, '["Rounding the lower back","Using momentum to jerk the weight up","Standing too upright"]'::jsonb, '["If you have lower back issues, consider chest-supported rows instead."]'::jsonb, '90-120 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Lat Pulldown', 'Back', ARRAY['Biceps', 'Rear Delts'], 'Machine', 'Beginner', '["Sit at a lat pulldown machine and adjust the knee pad.","Grab the wide bar with an overhand grip.","Pull the bar down to your upper chest while squeezing your shoulder blades together.","Slowly return the bar to the top."]'::jsonb, '["Pulling the bar behind the neck","Leaning too far back and using bodyweight to pull"]'::jsonb, '["Pulling behind the neck can cause rotator cuff injuries. Always pull to the front."]'::jsonb, '60-90 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Barbell Squat', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Core', 'Lower Back'], 'Barbell', 'Advanced', '["Position a barbell on your upper back and unrack it.","Stand with feet slightly wider than shoulder-width apart, toes pointed slightly out.","Brace your core and initiate the movement by pushing your hips back and bending your knees.","Squat down until your thighs are at least parallel to the floor.","Drive through your heels to stand back up."]'::jsonb, '["Knees caving inward (valgus)","Rounding the lower back (butt wink)","Not squatting deep enough"]'::jsonb, '["Always use safety pins or a spotter when lifting heavy.","Maintain a neutral spine at all times."]'::jsonb, '120-180 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Romanian Deadlift', 'Legs', ARRAY['Glutes', 'Lower Back', 'Core'], 'Barbell', 'Intermediate', '["Hold a barbell in front of you with an overhand grip.","Keeping a slight bend in your knees, hinge forward at the hips.","Lower the barbell down your legs until you feel a deep stretch in your hamstrings.","Squeeze your glutes and push your hips forward to return to the starting position."]'::jsonb, '["Bending the knees too much (turning it into a squat)","Rounding the back","Letting the bar drift away from the legs"]'::jsonb, '["Focus on the hip hinge. Do not force the range of motion if you lack flexibility."]'::jsonb, '90-120 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Leg Press', 'Legs', ARRAY['Glutes', 'Calves'], 'Machine', 'Beginner', '["Sit on the leg press machine and place your feet on the sled shoulder-width apart.","Unlatch the safety handles and lower the weight slowly until your knees are at 90 degrees.","Press the sled back up without locking your knees out completely.","Repeat for reps, then re-engage the safeties."]'::jsonb, '["Locking out the knees completely at the top","Lowering the weight too far so the lower back rounds off the pad"]'::jsonb, '["Never lock your knees backward under heavy load. It can cause severe injury."]'::jsonb, '90-120 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Overhead Press', 'Shoulders', ARRAY['Triceps', 'Upper Chest', 'Core'], 'Barbell', 'Intermediate', '["Stand with feet shoulder-width apart, holding a barbell at upper chest height.","Brace your core and squeeze your glutes.","Press the barbell straight up overhead until your arms are fully extended.","Lower it back down to your upper chest under control."]'::jsonb, '["Excessive arching of the lower back","Pushing the bar out in front instead of straight up","Using leg drive (which makes it a push press)"]'::jsonb, '["Be mindful of hitting your chin or nose on the way up. Move your head back slightly."]'::jsonb, '90-120 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Lateral Raises', 'Shoulders', ARRAY['Traps'], 'Dumbbell', 'Beginner', '["Stand holding a dumbbell in each hand by your sides.","Keep a slight bend in your elbows and raise your arms out to the sides.","Stop when your arms are parallel to the floor.","Lower the weights slowly back down."]'::jsonb, '["Swinging the torso to use momentum","Raising the arms too high (above parallel)","Leading with the wrists instead of the elbows"]'::jsonb, '["Do not use excessively heavy weights; focus on form and control to protect the shoulder joint."]'::jsonb, '60 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Bicep Curls', 'Biceps', ARRAY['Forearms'], 'Dumbbell', 'Beginner', '["Stand holding a dumbbell in each hand with a supinated (palms facing forward) grip.","Keep your upper arms stationary and curl the weights towards your shoulders.","Squeeze your biceps at the top.","Lower the weights slowly back to the starting position."]'::jsonb, '["Swinging the body","Letting the elbows drift forward","Not fully extending at the bottom"]'::jsonb, '["Use a controlled tempo to avoid elbow strain."]'::jsonb, '60 seconds', NULL);

INSERT INTO exercises (name, primary_muscle, secondary_muscles, equipment, difficulty, instructions, common_mistakes, safety_cautions, rest_recommendation, user_id)
VALUES ('Tricep Pushdowns', 'Triceps', ARRAY['Forearms'], 'Machine', 'Beginner', '["Attach a rope or straight bar to a high cable pulley.","Grab the attachment and stand with your elbows pinned to your sides.","Push the weight down until your arms are fully extended, squeezing your triceps.","Return slowly to the starting position."]'::jsonb, '["Letting the elbows flare out","Using bodyweight to push down","Short range of motion"]'::jsonb, '["Keep your wrists neutral to prevent wrist pain."]'::jsonb, '60 seconds', NULL);

